### ISSUE TITLE
Save partial output of incomplete components

### ISSUE THREAD

**Issue by thedroiddiv** [karya-inc/KaryaAndroid-Features#36]
## Description
Currently if user exits the task screen, only data for the component which are completed is saved and not for the current component which might have some partially filled data

## Proposed Solution
I have setup a mechanism to save the output and recover it when the component reloads. Currently it is implemented only in OpenComponent, well need to implement that in each component's controller.

## Steps
1. Override `destroy` method
2. Return the data and files so far from `destroy`
3. Load the initial data in when the controller is instantiated next time. Few components also have a `prefill` values associated with them. In these scenarios the preference would be `initialValue from mtaOutput` > `prefill` > `null/empty/initial`

## References
https://github.com/karya-inc/karya-android-client/pull/490

**Comment by thedroiddiv** [comment]
@atharvaTyagi @criticalAY Guys have a look. We can take this up independently, a single PR should just address only one component controller

@anuragshukla06

**Comment by criticalAY** [comment]
Do we need it for `UserAudioComponent`?

**Comment by thedroiddiv** [comment]
> Do we need it for `UserAudioComponent`?

Let's leave it for now.
