### ISSUE TITLE
[Enhancement] Segmentation Component

### ISSUE THREAD

**Issue by thedroiddiv** [karya-inc/KaryaAndroid-Features#6]
- [ ] **1. Irresponsive drag from edge** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/75c10257-c33f-4ebc-9cf1-7bfed935f5f3)

</details>

- [x] **2. Segment duration** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/c1120129-fb87-448e-b548-563fe11af9e5)

</details>

- [ ] **3. File not found** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/6fbafc8b-4026-423a-987a-3dcdc08d495b)

</details>

- [x] **4. Unable to move forward if recording < 1s** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/5209b66e-6053-4161-8238-8723dbfba04e)

</details>

- [x] **5. Long press pop-up** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/1c193157-09f4-4848-81e4-60ade8bee1bb)

</details>

- [x] **6. Segments grouping** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/e0b34c25-c40b-4495-ba1e-596c30c8b368)

</details>

- [ ] **7. Segment highlight** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/b814c1e5-898b-42d7-a0da-a70d6504221d)

</details>

- [x] **8. Auto Select segment** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/92b0a8f5-4351-4215-83bf-373940b4e1ad)

</details>

- [ ] **9. Add segment in mid and hide component** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/50d955cd-a75d-4394-bd57-9a481ddb1731)

</details>

- [ ] **10. Vertical Zooming vs Horizontal Zooming** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/f86f03db-6add-4602-a0ed-e903be8cb1fc)

</details>

- [x] **11. Wakelock** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/1e7b2e9e-cf32-4c02-af65-a6dfdb058236)

</details>

- [x] **12. Dashboard Cards chip color** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/69a319bb-c26d-4f1b-b072-e47e0df23606)

</details>

- [x] **13. Task Status section behaviour** <details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/3e5f5a4f-a770-4621-9b04-9098e9cbfeab)

</details>

**Comment by criticalAY** [comment]
> 12. Dashboard Cards chip color
It already has the mentioned color so I don't think we need to do anything here

**Comment by thedroiddiv** [comment]
Working on 6.

**Comment by thedroiddiv** [comment]
Done 4 and 6

**Comment by thedroiddiv** [comment]
Taking up 8

**Comment by thedroiddiv** [comment]
> 2. Segment duration

We actually need the start and end duration on the handles 1 and 2. 
Show segment duration in center is done.

**Comment by thedroiddiv** [comment]
> 9. Add segment in mid and hide component
How would I add a segment to the end? Select the last segment and click add?

> Is there use-case for the hide button?

Yes, if people want to scroll up and see, the hide button becomes helpful. On Some devices, the segmentation component might take up to 3/4th of the screen height

**Comment by thedroiddiv** [comment]
>  5. Long press pop-up

Required for dev related processes
